#!/bin/sh

cd /lustre1/u/u3006934/fluox_temp_rna/data

ml fastp FastQC MultiQC

fastqc *.fq.gz

multiqc ./

for R1 in *_1.fq.gz; do R2=${R1/_1.fq.gz}"_2.fq.gz"; r1paired=${R1/fq.gz}"paired.fastq"; r2paired=${R2/fq.gz}"paired.fastq"; r1unpaired=${R1/fq.gz}"unpaired.fastq"; r2unpaired=${R2/fq.gz}"unpaired.fastq"; html=${R1/_1.fq.gz}"fp.html"; json=${R1/_1.fq.gz}"fp.json"; fastp -i $R1 -I $R2 -o ../trimmed/$r1paired -O ../trimmed/$r2paired --unpaired1 ../trimmed/$r1unpaired --unpaired2 ../trimmed/$r2unpaired --detect_adapter_for_pe -r --cut_right --cut_right_mean_quality 30 -h ../trimmed/$html -j ../trimmed/$json; done

cd ../trimmed

fastqc *.fq.gz

multiqc ./